# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRp20IVffdQZvGsq8Sn3E1LKvwj_jL3o
"""

firstName = input("Enter your first name: ")
lastName = input("Enter your last name: ")

fullName= firstName + lastName

print("Hello", fullName, "!",  "Welcome to the Python Program")