# -*- coding: utf-8 -*-
"""pythonbasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRp20IVffdQZvGsq8Sn3E1LKvwj_jL3o

"""

a= int(input("Value of a: "))
b= int(input("Value of b: "))
c= a+b
d= a-b
e= a*b
f= a/b
print ("\nsum is: ",c)
print ("difference is: ",d)
print ("product is: ",e)
print ("quotient is: ",f)

firstName = input("Enter your first name: ")
lastName = input("Enter your last name: ")

fullName= firstName + lastName

print("Hello", fullName, "!",  "Welcome to the Python Program")
